definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  schema.OutMessageBodyParam:
    properties:
      origin_code:
        example: code
        type: string
      origin_model:
        example: model
        type: string
      payload:
        type: object
      routing_key:
        example: routing.key
        type: string
    required:
    - payload
    - routing_key
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/cron/resend:
    post:
      description: api resend `failed` out messages
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: api resend failed out messages
      tags:
      - Retry
  /api/v1/cron/retry:
    post:
      description: api resend `wait retry` in messages, message will change status to
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: api retry `wait retry` in messages
      tags:
      - Retry
  /api/v1/cron/retry_previous:
    post:
      description: api resend `wait retry previous` in messages, just retry in messages
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: api retry `wait retry previous` in messages
      tags:
      - Retry
  /api/v1/queue/messages:
    post:
      consumes:
      - application/json
      description: api publish out message to amqp
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schema.OutMessageBodyParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: publish message to amqp
      tags:
      - Out Messages
swagger: "2.0"
